services:
  flask:
    image: amihsan/flask-terraform-backend:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network

  react:
    image: amihsan/react-terraform-frontend:latest
    container_name: react-app
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
