---
- hosts: app_server
  become: true
  tasks:
    - name: Gather EC2 instance metadata
      ec2_metadata_facts:

    - name: Ensure Python 3 is installed
      package:
        name: python3
        state: present

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop all running Docker containers
      shell: |
        docker ps -q | xargs --no-run-if-empty docker stop
      ignore_errors: true

    - name: Remove all stopped Docker containers
      shell: |
        docker ps -a -q | xargs --no-run-if-empty docker rm
      ignore_errors: true

    - name: Remove all unused Docker images
      command: docker image prune -af

    - name: Remove all Docker images
      shell: |
        images=$(docker images -q)
        if [ -n "$images" ]; then
          docker rmi -f $images
        else
          echo "No images to remove"
        fi
      register: remove_images
      changed_when: "'No images to remove' not in remove_images.stdout"

    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        enabled: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg

    - name: Install Kubernetes tools
      package:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubectl
        - kubeadm

    - name: Enable and start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: Initialize Kubernetes control-plane
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      ignore_errors: true

    - name: Debug Kubernetes initialization result
      debug:
        var: kubeadm_init

    - name: Configure kubectl for root
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      when: kubeadm_init is not failed

    - name: Apply Flannel CNI plugin
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: kubeadm_init is not failed

    - name: Template Flask backend deployment file
      template:
        src: ./kubernetes/flask-deployment.yml.j2
        dest: /tmp/flask-deployment.yml

    - name: Template Flask backend service file
      template:
        src: ./kubernetes/flask-service.yml.j2
        dest: /tmp/flask-service.yml

    - name: Template React frontend deployment file
      template:
        src: ./kubernetes/react-deployment.yml.j2
        dest: /tmp/react-deployment.yml

    - name: Template React frontend service file
      template:
        src: ./kubernetes/react-service.yml.j2
        dest: /tmp/react-service.yml

    - name: Apply Flask backend deployment
      shell: kubectl apply -f /tmp/flask-deployment.yml

    - name: Apply Flask backend service
      shell: kubectl apply -f /tmp/flask-service.yml

    - name: Apply React frontend deployment
      shell: kubectl apply -f /tmp/react-deployment.yml

    - name: Apply React frontend service
      shell: kubectl apply -f /tmp/react-service.yml
