- hosts: app_server
  become: true
  tasks:
    - name: Gather EC2 instance metadata
      ec2_metadata_facts:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Install pip
      dnf:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3
        extra_args: --ignore-installed requests

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure ec2-user is in the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Ensure Docker network exists
      docker_network:
        name: app-network
        state: present

    - name: Stop and remove all Docker containers
      docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: yes
      loop: "{{ lookup('pipe', 'docker ps -a -q') | split('\n') }}"
      ignore_errors: true

    - name: Remove all unused Docker images
      command: docker image prune -af

    - name: Pull Flask backend image
      docker_image:
        name: amihsan/flask-terraform-backend:latest
        source: pull

    - name: Pull React frontend image
      docker_image:
        name: amihsan/react-terraform-frontend:latest
        source: pull

    - name: Run Flask container
      docker_container:
        name: flask-app
        image: amihsan/flask-terraform-backend:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
        networks:
          - name: app-network

    - name: Run React container with public IP as environment variable
      docker_container:
        name: react-app
        image: amihsan/react-terraform-frontend:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:3000"
        env:
          REACT_APP_API_URL: "http://flask-app:5000" # Use the Docker network name
        networks:
          - name: app-network

    - name: Install curl in React container
      docker_container_exec:
        name: react-app
        command: apk add --no-cache curl
        stdin: true

    - name: Debug public IP
      debug:
        msg: "Public IP: {{ ansible_ec2_public_ipv4 }}"

    - name: Check Flask endpoint from React container
      docker_container_exec:
        name: react-app
        command: >
          curl -s -o /dev/null -w "%{http_code}" http://flask-app:5000
      register: flask_status

    - name: Debug Flask endpoint status
      debug:
        msg: "Flask endpoint status code: {{ flask_status.stdout }}"
# - hosts: app_server
#   become: true
#   tasks:
#     - name: Gather EC2 instance metadata
#       ec2_metadata_facts:

#     - name: Install Docker
#       dnf:
#         name: docker
#         state: present

#     - name: Install pip
#       dnf:
#         name: python3-pip
#         state: present

#     - name: Install Docker SDK for Python
#       pip:
#         name: docker
#         executable: pip3
#         extra_args: --ignore-installed requests

#     - name: Start Docker service
#       service:
#         name: docker
#         state: started
#         enabled: yes

#     - name: Stop and remove all Docker containers
#       docker_container:
#         name: "{{ item }}"
#         state: absent
#         force_kill: yes
#       loop: "{{ lookup('pipe', 'docker ps -a -q') | split('\n') }}"
#       ignore_errors: true

#     - name: Remove all unused Docker images
#       command: docker image prune -af

#     - name: Pull Flask backend image
#       docker_image:
#         name: amihsan/flask-terraform-backend:latest
#         source: pull

#     - name: Pull React frontend image
#       docker_image:
#         name: amihsan/react-terraform-frontend:latest
#         source: pull

#     - name: Run Flask container
#       docker_container:
#         name: flask-app
#         image: amihsan/flask-terraform-backend:latest
#         state: started
#         restart_policy: always
#         published_ports:
#           - "5000:5000"

#     - name: Run React container with public IP as environment variable
#       docker_container:
#         name: react-app
#         image: amihsan/react-terraform-frontend:latest
#         state: started
#         restart_policy: always
#         published_ports:
#           - "80:3000"
#         env:
#           REACT_APP_API_URL: "http://{{ ansible_ec2_public_ipv4 }}:5000"

# - name: Run React container
#   docker_container:
#     name: react-app
#     image: amihsan/react-terraform-frontend:latest
#     state: started
#     restart_policy: always
#     published_ports:
#       - "80:3000"
