---
- hosts: app_server
  become: true
  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Install pip
      dnf:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Flask backend image
      command: docker pull amihsan/flask-terraform-backend:latest

    - name: Pull React frontend image
      command: docker pull amihsan/react-terraform-frontend:latest

    - name: Run Flask container
      command: docker run -d -p 5000:5000 --name flask-app amihsan/flask-terraform-backend:latest

    - name: Run React container
      command: docker run -d -p 80:3000 --name react-app amihsan/react-terraform-frontend:latest
