name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python for Ansible
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Ansible and required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve

      - name: Run Ansible playbook
        run: |
          ansible-galaxy collection install amazon.aws
          ansible-playbook -i ansible/hosts ansible/playbook.yml
