# .github/workflows/deploy.yml

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ansible

      - name: Build Docker images
        run: |
          docker build -t amihsan/flask-terraform-backend:latest ./backend
          docker build -t amihsan/react-terraform-frontend:latest ./frontend

      - name: Push Docker images
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push amihsan/flask-terraform-backend:latest
          docker push amihsan/react-terraform-frontend:latest

      - name: Run Terraform
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/hosts ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
